### ISSUE TITLE
New Provider?

### ISSUE THREAD

**Issue by guisea** [go-semantic-release/plugin-registry#4]
Hi @christophwitzko,  

I have created a new provider which works with Gitea.   Just wondering if how one might contribute this to be available for others?

My provider can be found at https://github.com/guisea/go-semantic-release-provider-gitea

Cheers

**Comment by christophwitzko** [comment]
Hi @guisea, that's very cool!

We have two options here:
1.) You leave the provider in your repository and people can use it with `--provider github:guisea/go-semantic-release-provider-gitea`. I would also link the provider in the main README (https://github.com/go-semantic-release/semantic-release?tab=readme-ov-file#plugins)
2.) We move the repository to this org where you will become the maintainer of the gitea provider. This way, I can add it to the plugin registry, and it will become an official go-semantic-release plugin.

Best,
Christoph

**Comment by guisea** [comment]
Ohh,  I did not know you could prefix the GitHub repo with GitHub: to do the download.  

I was manually creating the .semrel directory.  

I would be happy to have it as an official plugin I maintain

**Comment by christophwitzko** [comment]
Awesome @guisea, I invited you to the org. You can try now to transfer the repo to the org, but not 100% sure if it will work (due to permissions). Otherwise, you can add me as Admin to your repo, and I can do the transfer.

**Comment by guisea** [comment]
Cheers,

I have accepted the invite.  Will have a look at the transfer in a few
hours.

Regards

Aaron Guise

**Comment by guisea** [comment]
Cheers,

I have transferred the repository.  Probably needs to have a rename
from go-semantic-release-provider-gitea
just to provider-gitea
*. *

I don't seem to have rights to rename a repo :)

Regards

Aaron Guise

**Comment by christophwitzko** [comment]
Hi @guisea, I granted you Admin rights. You should have now full permission to manage the repo. Let me know if something is not working.
Once this PR (https://github.com/go-semantic-release/provider-gitea/pull/2) is merged your provider is published to the registry.
Best,
Christoph

**Comment by guisea** [comment]
Cheers,  all looks good.

Been busy today implementing a badge for coverage not reliant on third party such as codecov.

Nice and tidy now,  still able to have direct write access as before so thanks.
